name: docker

on:
  push:
    branches:
      - master

env:
  GO_VERSION: "1.22"
  CGO_ENABLED: 0
  GHCR_REPOSITORY: agologan/pgweb

jobs:
  docker-build:
    name: docker images
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure docker build context
        uses: docker/setup-buildx-action@v2

      - name: Build docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.GHCR_REPOSITORY }}:latest
          platforms: linux/amd64
          build-args: |
            "CGO_ENABLED=${{ env.CGO_ENABLED }}"
